### ISSUE TITLE
How to get it running on Synology NAS?

### ISSUE THREAD

**Issue by FlavioB79** [sethforprivacy/simple-monerod-docker#103]
Hi.
Is it possible to run this monerod-docker on Synology NAS? If yes, is there any how-to for it?
I've just tried downloading the "latest" tagged version, but it fails with:

_Add image from docker.io/sethforprivacy/simple-monerod:latest_
_Failed to pull image [manifest for sethforprivacy/simple-monerod:latest not found: manifest unknown: manifest unknown]._

Same thing happens, if I specify the version tag:

_Add image from docker.io/sethforprivacy/simple-monerod:v0.18.3.1_
_Failed to pull image [manifest for sethforprivacy/simple-monerod:v0.18.3.1 not found: manifest unknown: manifest unknown]._

What's wrong?

Thanks,
F.

**Comment by sethforprivacy** [comment]
Hi there, you should pull from GHCR now instead of Docker Hub, as I'll be removing Docker Hub usage soon:

`docker pull ghcr.io/sethforprivacy/simple-monerod:v0.18.3.1`

**Comment by FlavioB79** [comment]
Hi and thanks for your reply.
I've tried adding the GHCR registry this way, but it won't work:
[image: image.png]
When I try to use this registry, it tells me:
[image: image.png]
and it won't retrieve any list of available apps.

I'm very new to this, so any help would be appreciated. Is the path to the
GHCR registry wrong? Or what else am I missing?

Thanks,
Flavio.

https://www.instagram.com/boniforti_music
https://soundcloud.com/boniforti_music
https://bonny-j.bandcamp.com


Am Mo., 8. Jan. 2024 um 12:41 Uhr schrieb Seth For Privacy <
***@***.***>:

**Comment by sethforprivacy** [comment]
Those images didn't come through, could you try putting them directly in the Github issue instead of via email?

**Comment by FlavioB79** [comment]
> Those images didn't come through, could you try putting them directly in the Github issue instead of via email?

I just noticed it too. I'll repost later when I get back home. Thanks so far!
F.

**Comment by FlavioB79** [comment]
I've edited my comment with the images - now they are linked.
Thanks for your help - and let me know if there's a different/better way to add images here :-)
F.

**Comment by sethforprivacy** [comment]
AFAICT you can only do it from the command line for some reason?

https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret

**Comment by FlavioB79** [comment]
> AFAICT you can only do it from the command line for some reason?
> 
> https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret

Thank you Seth.
That's weird, I opened a support ticket at Synology. Let's see if their reply is the same as it was back in 2022. I'll report back asap.
F.

**Comment by FlavioB79** [comment]
> > AFAICT you can only do it from the command line for some reason?
> > https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret
> 
> Thank you Seth. That's weird, I opened a support ticket at Synology. Let's see if their reply is the same as it was back in 2022. I'll report back asap. F.

This is what Synology support just replied:

_Unfortunately, it is a current limitation that the Container Manager does not support the authentication token which Github / Gitlab is using currently._

Does this sound correct? I mean: is Github in fact using an authentication token to access it for pulling?
F.

**Comment by sethforprivacy** [comment]
> > > AFAICT you can only do it from the command line for some reason?
> > > https://stackoverflow.com/questions/73825556/adding-ghcr-github-docker-regustry-to-synology-docker-results-in-registry-ret
> > 
> > 
> > Thank you Seth. That's weird, I opened a support ticket at Synology. Let's see if their reply is the same as it was back in 2022. I'll report back asap. F.
> 
> This is what Synology support just replied:
> 
> _Unfortunately, it is a current limitation that the Container Manager does not support the authentication token which Github / Gitlab is using currently._
> 
> Does this sound correct? I mean: is Github in fact using an authentication token to access it for pulling? F.

Not AFAIK when just pulling images.

**Comment by FlavioB79** [comment]
Indeed I was able to pull the image via CLI with the command you initially
told me to use.
The daemon is starting just fine and is downloading/syncing. Now I just got
another question: I have mapped the volume of the container to a shared
folder on my Synology NAS. Shouldn't I see files in this shared folder now?
The mapping is as follows: /docker/monero-blockchain --> /root.bitmonero
(r/w)
Thanks for your help,
F.

https://www.instagram.com/boniforti_music
https://soundcloud.com/boniforti_music
https://bonny-j.bandcamp.com


Am Di., 9. Jan. 2024 um 20:23 Uhr schrieb Seth For Privacy <
***@***.***>:

**Comment by FlavioB79** [comment]
HI.
I was able to set the permissions on my shared folder (on the NAS) to belong to user 1000 and group 1000 (the ones set inside of the container). Now it works.
Thanks,
Flavio.
