### ISSUE TITLE
is this a security concern?

### ISSUE THREAD

**Issue by wirytiox** [sethforprivacy/simple-monerod-docker#105]
![image](https://github.com/sethforprivacy/simple-monerod-docker/assets/79142532/543c9c04-acb9-47e6-a16c-580a5832479c)
i found this in docker desktop on windows and i want to know if i should be concerned, please tell me and i research how to add more data. or maybe is not that problematic, i am new to this, sorry.

**Comment by sethforprivacy** [comment]
Hard to tell exactly how much this is possible to be patched, I rebuild my image weekly with the latest security updates via apt to avoid as much as possible, but if this is a vuln in an underlying dependency that is as up to date as possible there isn't much I can do.

I would think this could be ignored, but you're welcome to dig into it more if you'd like!
