### ISSUE TITLE
Use `get_height` for health check

### ISSUE THREAD

**Issue by SamsungGalaxyPlayer** [sethforprivacy/simple-monerod-docker#112]
https://github.com/sethforprivacy/simple-monerod-docker/blob/ab316cb1809b34fc7aa6035a212a379b397aa9eb/Dockerfile#L190

`get_height` is significantly less resource intensive than `get_info`.

**Comment by sethforprivacy** [comment]
Ah, amazing, had no idea!

Merged in https://github.com/sethforprivacy/simple-monerod-docker/commit/3a7ec6abed0fa4900c27e6f28d642aaecb66ce9b

**Comment by hundehausen** [comment]
I made some tests with Postman. I see similar response times for both calls, but get_height is smaller in terms of bytes.
