### ISSUE TITLE
Cant sync

### ISSUE THREAD

**Issue by tortxoFFoxtrot** [sethforprivacy/simple-monerod-docker#136]
It starts off syncing ok, but eventually it is so slow. I have only 108939 left to sync, but it just gets slower and slower it tells me it is going to take 3 months to synk this last 100k blocks that makes no sense?

`monero  | 2024-08-10 11:20:36.463       I Synced 3103165/3212104 (96%, 108939 left, 0% of total synced, estimated 3.0 months left)`

**Comment by hundehausen** [comment]
Is your volume on a HDD or SSD?

**Comment by tortxoFFoxtrot** [comment]
> Is your volume on a HDD or SSD?

It is a RAIDZ1 comprised of 4x16TB HDD. I am running monerod on the device, there is 400MB/s throughput onto this raid locally on the NAS (it's not reaching it by network share the raid is mounted locally).

**Comment by sethforprivacy** [comment]
The most likely answer here is the instant operations (IOPS) of your HDDs are far too low and unable to keep up with the IOPS-intensive stage of sync after you've gotten past the hard-coded checkpoint.

There is a checkpoint hard-coded in each release of Monero that by default makes sync up that point only check block headers, so it's far easier to sync. After the checkpoint your node starts checking all Monero transactions, which is wildly more IOPS-dependent. This is why it's always recommended to use an SSD - it's not _just_ about bandwidth, it's really more about IOPS where SSDs obliterate spinners.

**Comment by tortxoFFoxtrot** [comment]
> The most likely answer here is the instant operations (IOPS) of your HDDs are far too low and unable to keep up with the IOPS-intensive stage of sync after you've gotten past the hard-coded checkpoint.
> 
> There is a checkpoint hard-coded in each release of Monero that by default makes sync up that point only check block headers, so it's far easier to sync. After the checkpoint your node starts checking all Monero transactions, which is wildly more IOPS-dependent. This is why it's always recommended to use an SSD - it's not _just_ about bandwidth, it's really more about IOPS where SSDs obliterate spinners.

Why are the IOPS so much more than Bitcoin? Surely the bulk of the work is done by the CPU what does the disk need to do? That doesn't seem to make much sense. Even one just of my drives is rated for 285MB/s I don't think it is a choke point. The drive doesn't process the data.

**Comment by sethforprivacy** [comment]
IOPS != bandwidth! They are very different things, and IOPS is far more important for any blockchain sync.

When verifying a Bitcoin transaction, you have to go through the entire blockchain and find/verify the input UTXOs along with the rest of the transaction details.

When verifying a Monero transaction, you have to go and find 16 transaction outputs _per input_ to find and verify, and they also each have more intensive cryptography to verify. It's a much more IOPS intensive process, though even Bitcoin is recommended to be run on an SSD if at all possible these days.

**Comment by tortxoFFoxtrot** [comment]
I have a PC with an SSD I suppose I can gopy the blockchain over so far to it and fire up monerod see if it makes a difference.
