### ISSUE TITLE
Potential Dockerfile documentation ''bug''

### ISSUE THREAD

**Issue by CryptoGrampy** [sethforprivacy/simple-monerod-docker#17]
Hi Seth-

I just want to preface this by saying that I'm 100% not a pro on this stuff, but when I wrote my simple monerod docker compose file, I noticed that when I changed the volume specified in this documentation- something like bitmonero:/home/monero, to something that accommodated a volume on my personal computer/that utilized the default blockchain location the Monero GUI uses: ~/.bitmonero:/home/monero, I found that the Docker container created a .bitmonero directory IN my .bitmonero directory on my host machine, and I ended up with something like: ~/.bitmonero/.bitmonero/lmdb.  

Additionally, when I tried ~:/home/monero, my host system's .bitmonero directory mapped perfectly to the .bitmonero directory created in the container, HOWEVER, I found out that this method copied all of my home directory files into the container, which is kind of a nono. 

I believe what's currently happening via the documented startup of running the Dockerfile, is that a named Docker volume (bitmonero) is created on the host system, but that volume is mapped to /home/monero, and not actually mapped to /home/monero/.bitmonero on the container.  To the end user, this makes no difference as most people don't interact much with their host docker volumes (where they would likely find it contains the .bitmonero folder as well as any other files in the container 'shome directory), and the container is doing exactly what it's supposed to- it's downloading the Monero blockchain, starting up Monerod, and plumbing all of the ports.

My proposal would be to update the documentation to something like:  bitmonero:/home/monero/.bitmonero   ... I believe this change would have zero effect on anyone using the 'bitmonero' named docker volume, but it will be mapped correctly to the .bitmonero directory in the container.  And to users looking to map their .bitmonero directories running in weird places on their regular computers, they will understand that they need to map .bitmonero:/home/monero/.bitmonero.  

A good example of this documentation is the official nginx container where many people copy static html files from a host machine to a very specific folder for hosting purposes: https://www.docker.com/blog/how-to-use-the-official-nginx-docker-image/

**Comment by sethforprivacy** [comment]
Thanks for the issue! resolved via https://github.com/sethforprivacy/simple-monerod-docker/commit/6d7f131ece223ed7488993247dec55d72e4fc75d
