### ISSUE TITLE
Monerod version 'out of sync' with version needed by p2pool

### ISSUE THREAD

**Issue by marvin8** [sethforprivacy/simple-monerod-docker#20]
Looks like the docker images produced by this repo are lagging what's needed to run the p2pool docker image published by you as well.

See [issue 3](https://github.com/SChernykh/p2pool/issues/31#) on the p2pool repo.

Is there a better way to keep the docker images for p2pool and the corresponding version of monerod in sync? Currently I have `image: sethsimmons/simple-monerod:p2pool-api-v0.17` in my docker-compose.yml file.

For more context:      
I did a `docker-compose pull` this morning that updated the p2pool image (`image: sethsimmons/p2pool:latest`). The monero image did not receive an update during this pull.

**Comment by sethforprivacy** [comment]
I don't think I'll spend the time setting up CI for this version as it should soon be included in a release, but feel free to fork and make the changes or submit a PR.

In the meantime I'll kick off a new build now so it's up to date (for now, at least).
