### ISSUE TITLE
ARM compatible?

### ISSUE THREAD

**Issue by leonarzoh** [sethforprivacy/simple-monerod-docker#21]
just to clarify, the monero node docker implementation is also compatible with ARM or just x86/x64? I'm asking because I wanna install it on a Rasp device. Tbh, PiNode XMR implementation seems a bit complicated and I rather use this one.

**Comment by sethforprivacy** [comment]
I believe my image will only work with x86/64, it is not a multi-arch image but I would welcome any pull requests that could make it multi-arch!

**Comment by leonarzoh** [comment]
confirm. I created a Brazillian Portuguese guide using your implementation to help Brazilians to install a node, I hope you don't mind https://medium.com/@lozbek/guia-monero-node-com-docker-945e4dc53b17
please let me know if the image update to multi-arch so I can update the article

**Comment by Aaronstotle** [comment]
I have built a test image and uploaded into a test docker repo. I don't have a raspberry pi to test out, so @leonarzoh  please feel free to try it and let me know if works.


The image can be downloaded by running `docker pull ayayronstotle/monero_multiarch:seth`

**Comment by theanonymousexyz** [comment]
@leonarzoh there's ARMv8 support now :+1:
