### ISSUE TITLE
RPC Update v3.5 -> v3.8

### ISSUE THREAD

**Issue by Qu4ndo** [sethforprivacy/simple-monerod-docker#22]
P2Pool seems to not like the current RPC Version of the monerod Docker.
Is there a fix to this coming soon?

P2Pool Error:
"monerod RPC v3.5 is incompatible, update to RPC >= v3.8"

**Comment by sethforprivacy** [comment]
Are you using the right tag for this image when used with p2pool?

https://blog.sethforprivacy.com/guides/run-a-p2pool-node/#download-and-run-monerod-and-p2pool-via-docker

`sethsimmons/simple-monerod:p2pool-api-v0.17`

There are still some fixes/improvements that are yet to be released in an official release, so I'm keeping the tag `p2pool-api-v0.17` up to date with the latest fixes in the `release-v0.17` branch of Monero.

**Comment by Qu4ndo** [comment]
Okay, that was the problem...

I've been using the `latest ` release which is `v0.17` (following the dockerhub info).
After changing it to `release-v0.17` it worked without a problem.

Sorry for the stupid issue and thanks for the awesome work!

**Comment by sethforprivacy** [comment]
> Okay, that was the problem...
> 
> I've been using the `latest ` release which is `v0.17.2.3` (following the dockerhub info). After changing it to `release-v0.17` it worked without a problem.
> 
> Sorry for the stupid issue and thanks for the awesome work!

Not stupid at all, definitely an understandable issue if you weren't coming directly from one of my guides etc!

Glad that sorted it for you.
