### ISSUE TITLE
tor-hidden-service docker container reference is amd64; arm64 option?

### ISSUE THREAD

**Issue by PLK2** [sethforprivacy/simple-monerod-docker#57]
The following code references an amd64 docker container:

`docker run -d --restart unless-stopped --link monerod:monerod --name tor --volume tor-keys:/var/lib/tor/hidden_service/ goldy/tor-hidden-service`

This won't run on my arm64 RockPro64. Is there an alternative container? Otherwise, perhaps add a note in your guide about this.

**Comment by sethforprivacy** [comment]
Unfortunately there isn't an ARM image for that AFAIK.

I'll need to add a note to the guide, as people running ARM should use the standard Tor binaries/approach mentioned elsewhere in the same guide (the non-Docker approach to Tor hidden services).
