### ISSUE TITLE
Healthcheck during sync on RP4 not reliable

### ISSUE THREAD

**Issue by mondsen** [sethforprivacy/simple-monerod-docker#73]
I am currently syncing on a RP4 with an extern SSD and I am in the last 2h of the sync process. What I have noticed is that the container is oven reported as unhealthy. This is not a real problem but can be irritating to users. 

What I have noticed is that assumingly due to high CPU load my node sometimes requies up 25s for the returnvalues for the healthcheck (curl --fail http://localhost:18089/get_info). 

I see two solutions: increase timeout or state this in your readme (low end hardware can result in this during sync). I will report back if the problem occurs during normal sync state.

**Comment by sethforprivacy** [comment]
Thanks for the report! That is definitely an issue with the healthcheck as recommended, but as it's not part of the image and entirely configurable I'm not sure it's worth changing.

**Comment by mondsen** [comment]
What do you mean it is not part of the image? This is what is in your Dockerfile:

````
# Add HEALTHCHECK against get_info endpoint
HEALTHCHECK --interval=30s --timeout=5s CMD curl --fail http://localhost:18081/get_info || exit 1
````

For me it is fine to leave it like this, but then maybe update readme.md to give a hint that this can occur during sync.
