### ISSUE TITLE
Syncing gets stuck, and container reports unhealthy.

### ISSUE THREAD

**Issue by helloeverything1** [sethforprivacy/simple-monerod-docker#82]
I set the container up for the first time, syncing to hard drives because I don't have a large enough SSD for it. However, it has been syncing for a day or two now, and still hasn't finished. Every 15-20 minutes, the container will fix itself and sync for a few seconds, but then it stops again and waits another 15-20 min. I installed iotop, and the monerod process is using 99.99% of IO most of the time, although it seems to drop down when it starts syncing again. Whats going on here?

**Comment by helloeverything1** [comment]
ahh, well, its a zfs mirrored drive that is connected to the VM that docker runs on with NFS, so all those steps must be slowing it way down. Will it be ok-ish once the node is synced, or will it always have awful performance?

**Comment by kn0wmad** [comment]
Just realized what repo this was in.  Sorry I thought it was the StartOS Monero package.  You might be alright following IBD, but a complex setup can certainly cause issues.  I'll default to the repo owner for recommendations here.

**Comment by sethforprivacy** [comment]
> ahh, well, its a zfs mirrored drive that is connected to the VM that docker runs on with NFS, so all those steps must be slowing it way down. Will it be ok-ish once the node is synced, or will it always have awful performance?

It will be fine once it's done with IBD, but definitely not a recommended setup for a performant node. If you can wait a week or so for IBD then you'll be OK, though.
